base_url = "https://wildrydegames.github.io/danryder.dev/"
title = "Dan Ryder"
description = "Game dev, systems thinking, building cool things."
compile_sass = false
build_search_index = true

# ✅ correct key in Zola 0.21
generate_feeds = true
feed_filenames = ["atom.xml"]